### ISSUE TITLE
sds-button 

### ISSUE THREAD

**Issue by adelinemdavis** [GSA/sam-styles#469]
When combining the sds-button--circle the inner icon is not centered within the circle but slightly above center. This is also exaggerated when usa-button--base  and usa-button--small classes is added to the class, but that may be coloring only.

sds-button--circle with no other classes:
<img width="45" alt="sds-button--circle" src="https://user-images.githubusercontent.com/88726713/128888809-7a031de7-b10b-4371-bc30-ba4b37580b57.PNG">

sds-button--circle + usa-button--base:
<img width="33" alt="sds-button--circle-sds-button--base" src="https://user-images.githubusercontent.com/88726713/128889074-0a2ca910-4cd6-4f04-b0d6-3f223521334a.PNG">

sds-button--circle +usa-button--base + sds-button--small
<img width="25" alt="sds-button--circle-sds-button--base-sds-button--small" src="https://user-images.githubusercontent.com/88726713/128889248-e60db508-4af7-4d06-80c1-e1c9c1c2c652.PNG">

**Comment by cwolf10** [comment]
Hi @adelinemdavis, I have added a class to usa-icon, icon-display-block., in version [0.0.7](https://github.com/GSA/ngx-uswds-icons/releases/tag/v0.0.7) of ngx-uswds-icons You should be able to pass it to the iconClasses input `<usa-icon [iconClasses]="'icon-display-block'">` to remove the spacing at the bottom of the icon, fixing the alignment.
