### ISSUE TITLE
(Angular 13) Applies to Formly Filters - A space between a border and a first list item is smaller than it used to be.

### ISSUE THREAD

**Issue by wonko-gsa** [GSA/sam-styles#580]
1. We've updated to **Angular 13** and **@gsa-sam packages** as below: 

```
    "@gsa-sam/components": "13.0.0-beta.3",
    "@gsa-sam/layout": "13.0.0-beta.1",
    "@gsa-sam/layouts": "13.0.0-beta.0",
    "@gsa-sam/ngx-uswds": "13.0.0-beta.1",
    "@gsa-sam/ngx-uswds-icons": "13.0.0-beta.2",
    "@gsa-sam/sam-formly": "13.0.0-beta.3",
    "@gsa-sam/sam-material-extensions": "13.0.0-beta.3",
    "@gsa-sam/sam-styles": "0.0.145",
    "@gsa-sam/shared": "13.0.0-beta.1",
```

2. And I found that a space between a border and a first list item is **smaller than** it used to be which are in following places in the screenshot: 
* Notes: The right side is COMP **without** the updates, and the left side is localhost **with** the updates in the screenshot.

a. 
![2b  exclusion-label-error](https://user-images.githubusercontent.com/117218338/199344870-70eb317d-2f23-4f20-8e3c-67de9ed00781.png)

b. 
![8  margin-top-fed-entities-entity-status](https://user-images.githubusercontent.com/117218338/199344973-e7ea3b34-e1c7-42b2-83fe-489aae4a922f.png)

c.
![17  margin-exclusions-legacy-ct-codes-Exclusions_Type](https://user-images.githubusercontent.com/117218338/199345174-a64adfef-6b17-485b-8dcd-6abc0984ebb5.png)

3. It seems those changes are coming from updating CSS styles below. Those changes are applied to other places as well, however it seems except for list-items with checkboxes, they look okay IMO.  
* Notes: The right side is COMP with the updates, and the left side is MINC without the updates in the screenshot.
![issue-group-4-ref-8-small-top-margin-checkbox](https://user-images.githubusercontent.com/117218338/199344418-90cbf049-aebb-4869-9ab0-be8492cc74e3.PNG)

```
formly-form .usa-form-group {
    margin-top: 0!important;
}
```

and 

```
.margin-y-0 {
    margin-top: 0!important;
    margin-bottom: 0!important;
}
```

4. Here is code snippet for formly config: 

```javascript
fedHsFields: FormlyFieldConfig[] = [
    this.fedHsFieldKeyword,
    this.searchEntityConfig,
    {
      key: 'status',
      templateOptions: { label: 'Entity Status', group: 'accordion' },
      fieldGroup: [
        {
          key: 'statusId',
          id: 'status',
          type: 'multicheckbox',
          templateOptions: {
            label: 'Entity Status',
            labelClass: 'usa-sr-only',
            hideOptional: true,
            options: [
              {
                key: '1,2',
                value: 'Work in Progress Registration'
              },
              {
                key: '3',
                value: 'Submitted Registration'
              },
              {
                key: '4',
                value: 'Active Registration'
              },
              {
                key: '7',
                value: 'Inactive Registration'
              },
              {
                key: '12',
                value: 'ID Assigned'
              }
            ]
          },
          hooks: {
            onInit: (field: FormlyFieldConfig) => {
              if (this.queryParams.statusId != null) {
                const stats = this.queryParams.statusId.split(',');
                const val = {};
                for (const stat of stats) {
                  if (stat === '1' || stat === '2') {
                    val['1,2'] = true;
                  } else {
                    val[stat] = true;
                  }
                }
                field.formControl.setValue(val);
              }
            }
          }
        }
      ],
    },
    this.expirationDateConfig,
    this.fedHsFieldAddressUpdate
  ];
```

**Comment by yerramshilpa** [comment]
Issues resolved with latest versions of sds 

@gsa-sam/components@13.0.1
@gsa-sam/sam-formly@13.0.1
@gsa-sam/sam-styles@0.0.147
